name: serverListSMapi
version: '${version}'
main: ramune314159265.spigotserverlistsmapi.ServerListSMapi
api-version: '1.18'
load: STARTUP
authors: [ramune314159265]
description: Display the list of servers in the Chest GUI from the serverManager API
commands:
  serverlist:
    aliases: [ svl ]
    description: Open Server List
    permission: serverlist.command.serverlist
  serveropenlist:
    aliases: [ svol ]
    description: Open Server Startup List
    permission: serverlist.command.serveropenlist

permissions:
  serverlist.command.*:
    description: Allows you to perform commands in this plugin.
    children:
      serverlist.command.serverlist: true
  serverlist.command.serverlist:
    description: Allows you to perform /serverlist command.
    default: true
  serverlist.command.serveropenlist:
    description: Allows you to perform /serveropenlist command.
    default: true